# 一个线程运行时发生异常会怎样



① **如果该异常被捕获或抛出，则程序继续运行。** 
② **如果异常没有被捕获该线程将会停止执行。** 

Thread.UncaughtExceptionHandler是用于处理未捕获异常造成线程突然中断情况的一个内嵌接口。**当一个未捕获异常**将造成线程中断的时候JVM会使用Thread.getUncaughtExceptionHandler()来**查询线程的UncaughtExceptionHandler**，并将线程和异常作为参数传递给handler的uncaughtException()方法进行处理

![img](https://img-blog.csdnimg.cn/2019080315565782.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0ZseV9hc190YWRwb2xl,size_16,color_FFFFFF,t_70)。

### 实例： 


1.未处理的RuntimeException，发生异常后程序停止运行

public class Main1 {

  public static void main(String[] args){
      int x = 1;
      x = x / 0;
      System.out.println("x = "+x);
  }
}

输出：

Exception in thread "main" java.lang.ArithmeticException: / by zero
  at microsoft2018.Main1.main(Main1.java:14)

 


2.程序处理RuntimeException，发生异常后继续运行

public class Main1 {

  public static void main(String[] args){
    try{
      int x = 1;
      x = x / 0;
    }catch(Exception e){
      System.out.println("除0错误");
      e.printStackTrace();
    }

​    System.out.println("继续执行")；
  }
}

输出：

除0错误
java.lang.ArithmeticException: / by zero
  at microsoft2018.Main1.main(Main1.java:14)

继续执行



> 线程异常处理可以参考：[在线程中你怎么处理异常](在线程中你怎么处理异常.md)